test-vector:
  script: "make tests; ./bin/test_libmatrix"
  tags:
    - c++

test-matrix:
  script: "make tests; ./bin/MatrixTest"
  tags:
    - c++
    - cppunit

test-object3D:
  script: "make tests && ./bin/Object3DTest"
  tags:
    - c++
    - cppunit
    
test-triangle:
  script: "make tests && ./bin/TriangleTest"
  tags:
    - c++
    - cppunit

quality:
  script: "sonar-scanner"
  tags:
    - c++
    - sonar
